#!/bin/bash

# Note: Helm 3 no longer ships with a default chart repository. The
# helm repo command group provides commands to add, list, and remove
# repositories.
#
#  $ helm repo add stable https://kubernetes-charts.storage.googleapis.com
#  $ helm repo update

kubectl create namespace prometheus
helm install prometheus stable/prometheus \
    --namespace prometheus \
    --set alertmanager.persistentVolume.storageClass="gp2",server.persistentVolume.storageClass="gp2"
